apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: mongodb-helm
  namespace: argocd

spec:
  project: default

  source:
    chart: mongodb-helm
    repoURL: 'https://github.com'
    path: '7-k8s/07-helm-roboshop/01-mongodb'
    targetRevision: main
    helm: 
      valuesFiles:
        - values.yaml
       # - values-dev.yaml
  destination:   # Destination configuration pointing to the target cluster and namespace
    server: https://kubernetes.default.svc
    namespace: roboshop-dev

  syncPolicy:
    automated:
      prune: true     # This will delete resources that are no longer defined in the Git repository.
      selfHeal: true   # This will automatically apply changes made to the resources in the Git repository.