apiVersion: v1
kind: Secret
metadata:
  name: github-devops-project-secret
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
type: Opaque
data:
  type: Z2l0                                 # FIXED: Now decodes correctly to "git"
  url: aHR0cHM6Ly9naXRodWIuY29tL3BhbmRhbGFwYWR1L215LUFXUy1EZXZPcHMtUHJvamVjdC5naXQ= # "https://github.com"
  username: cGFuZGFsYXBhZHU=                 # "pandalapadu"
  password: Z2l0aHViX3BhdF8xMUFPRDdRNVEwNjFoZTAxTnBBTkZ0X3VVd3BBS2RJMzNZNEN6YkcxSHFGV1pQWDlqeDdudlBrSmhqZHdtdXo5b2EzSUlWNjRWQTBQTWhEcUY2
